# Aliases
a = "http://www.yah.o"
cfg = "https://example.com"
g = "https://www.google2.com"
gc = "https://example.com"
q = "https://example.com"
y = "https://www.yahoo.com"
y4 = "https://www.yahoo4.com"

